spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/user/**

        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/auth/**

        - id: auth-service-api-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
        - name: Auth Service
          url: /v3/api-docs/auth-service
        - name: User Service
          url: /v3/api-docs/user-service