spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                pattern: /api/v1/auth/**
server:
  port: 8080