spring:
  application:
    name: auth-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  data:
    redis:
      username: default
      password:
      database: 0
server:
  port: 8081
