name: Build

on:
  push:
    branches:
      - main

jobs:
  build-micro-services:
    name: 构建微服务
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 配置 JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: 'maven'

      - name: 配置 Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: 配置 Docker
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 安装Commons模块
        run: mvn -f commons install

      - name: 打包Eureka Server
        run: mvn -f eureka-server package

      - name: 打包Config Server
        run: mvn -f config-server package

      - name: 打包Gateway Server
        run: mvn -f gateway-server package

      - name: 打包User Service
        run: mvn -f user-service package

      - name: 打包Auth Service
        run: mvn -f auth-service package

      - name: 上传工件
        uses: actions/upload-artifact@v4
        with:
          name: micro-services
          path: '*/target/*.jar'
          compression-level: '9'

      - name: 上传至Docker - Eureka Server
        uses: docker/build-push-action@v6
        with:
          context: eureka-server
          push: true
          tags: mioyisama/eureka-server:latest

      - name: 上传至Docker - Config Server
        uses: docker/build-push-action@v6
        with:
          context: config-server
          push: true
          tags: mioyisama/config-server:latest

      - name: 上传至Docker - Gateway Server
        uses: docker/build-push-action@v6
        with:
          context: gateway-server
          push: true
          tags: mioyisama/gateway-server:latest

      - name: 上传至Docker - User Service
        uses: docker/build-push-action@v6
        with:
          context: user-service
          push: true
          tags: mioyisama/user-service:latest

      - name: 上传至Docker - Auth Service
        uses: docker/build-push-action@v6
        with:
          context: auth-service
          push: true
          tags: mioyisama/auth-service:latest