name: Build

on:
  push:
    branches:
      - main

jobs:
  build-micro-services:
    name: 构建微服务
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 部署 JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: 部署 Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: 构建 Commons
        run: mvn -f commons install

      - name: 构建 Eureka Server
        run: mvn -f eureka-server package

      - name: 上传工件 - Eureka Server
        uses: actions/upload-artifact@v4
        with:
          name: eureka-server.jar
          path: eureka-server/target/eureka-server-*.jar

      - name: 构建 Config Server
        run: mvn -f config-server package

      - name: 上传工件 - Config Server
        uses: actions/upload-artifact@v4
        with:
          name: config-server.jar
          path: config-server/target/config-server-*.jar

      - name: 构建 Gateway Server
        run: mvn -f gateway-server package

      - name: 上传工件 - Gateway Server
        uses: actions/upload-artifact@v4
        with:
          name: gateway-server.jar
          path: gateway-server/target/gateway-server-*.jar

      - name: 构建 User Service
        run: mvn -f user-service package

      - name: 上传工件 - User Service
        uses: actions/upload-artifact@v4
        with:
          name: user-service.jar
          path: user-service/target/user-service-*.jar

      - name: 构建 Auth Service
        run: mvn -f auth-service package

      - name: 上传工件 - Auth Service
        uses: actions/upload-artifact@v4
        with:
          name: auth-service.jar
          path: auth-service/target/auth-service-*.jar
